### PR TITLE
Updated Indian Regional Names

### PR DESCRIPTION
**Pull request by praveenscience**
Added Indian names.

### CODE REVIEW

**Comment by benkeen** [comment]
Excellent, thanks @praveenscience!

**Comment by benkeen** [comment]
I haven't merged yet because there's a conflict. When I get a little time I'll do a rebase and get it merged.

**Comment by praveenscience** [comment]
Sure... Lemme know if you need any issues.

**Comment by praveenscience** [comment]
@benkeen Any updates?

**Comment by benkeen** [comment]
Hey @praveenscience - awfully sorry for the wait. I'll look at this today. Not sure what the process is here... I may need to do a rebase against your branch which you'll need to merge in, in order to allow me to merge... we'll see.

**Comment by benkeen** [comment]
Merged, thanks @praveenscience! This will be included in the next release.

**Comment by praveenscience** [comment]
Yay!!! :)

**Pull request merged**
