### PR TITLE
Bugfix for variable separator length

### PR DESCRIPTION
**Pull request by psauvetre**

### CODE REVIEW

**Comment by benkeen** [comment]
Hi @psauvetre, sorry I missed this. Could you explain the bug exactly? I'm not too familiar with that Data Type, but entering something like `++|-` seems to work correctly - the output is:

```javascript
	"data": [
		[
			"345528-1232"
		],
		[
			"074570++4700"
		],
		[
			"289500-3933"
		],
		[
			"929569-9400"
		],
		[
			"775711++3563"
		]
```

**Comment by psauvetre** [comment]
Hi @benkeen ! 
No problem! It has been a while ago now but I think I fixed this problem already, for both data types, PersonalNumber and OrganisationNumber.

**Comment by benkeen** [comment]
Hey again, sheesh I'm bad at getting back to you! 

I don't quite follow... you say you've fixed the problem - do you mean in a different commit? I also see you did a rebase, so it seems like maybe this PR fixes the problem? In the previous comment I asked:

Could you explain the bug exactly? I'm not too familiar with that Data Type, but entering something like `++|-` seems to work correctly. 

Thanks!

**Comment by psauvetre** [comment]
Hi! 
Yes I fixed the bug in commit 2895224, after writing this bug report :)
PersonalNumber data type is for generating fake yet realistic swedish personal numbers, which are in the form yyyymmdd-xxxx, where:
yyyy: year
mm: month
dd: day
xxxx: 4 siffers where the third one indicates the person's gender, and the last one is a checksum.
The separator separates the yyyymmdd field from the xxxx field, it is most usually '-' but can even be '+' or empty.
The OrganisationNumber data type is quite similar but is used for swedish organisations (for example companies).
Best regards,

Pascal.

**Pull request closed without merging**
