### PR TITLE
Fixed instances of short region where region code used was greater than 3 characters

### PR DESCRIPTION
**Pull request by mansoorjamal**
I've changed all instances of regionShort that were > 3 characters to 3 characters.

One concern is the change in Chili - Chili uses roman numerals for region short. VIII (8) is larger than 3 chars, so I have changed it to the number 8.

For consistency, should I go ahead and change all region shorts in Chile to be base 10 numbers, or is there a particular reason behind the roman numerals?

Thanks,
Mansoor

### CODE REVIEW

**Comment by benkeen** [comment]
I think perhaps instead of truncating all regions, the database field size itself should be increased in the installation code. Honestly, it doesn't matter how large the field itself gets in the database - that was kind of dumb of me setting it so low, to be honest. :) I mean, short versions of regions may differ in sizes for different countries - I don't think there's anything wrong with that. The purpose of the field isn't to enforce a particular size, rather to just store a shortened version of the regions that has meaning for that country. So I'd suggest leaving those actual region values alone and tweaking the installation code to crank up the size to realistically accommodate any value.

> For consistency, should I go ahead and change all region shorts in Chile to be base 10 numbers, or is there a particular reason behind the roman numerals?

Good question! According to Wikipedia, apparently Chilean regions *are* given a roman numeral - so I guess that's right. Huh! 
https://en.wikipedia.org/wiki/Regions_of_Chile

**Comment by mansoorjamal** [comment]
Chilean regions... Learn something new every day!

Thanks for the leg work on looking up the Chilean roman numeral thing.

I don't think there is a well defined standard for a region's short code - In a past internationalization project, we left it the same size as the region name itself. Many regions, especially in Asian countries, do not seem to have shorter names.

For example, consider https://en.wikipedia.org/wiki/Telangana (The Indian state housing their Silicon Valley, aka Hyderabad). There is no abbreviation for it defined in the right side column (contrast with https://en.wikipedia.org/wiki/Ontario, Ontario Canada, which defines ON).

Based on your thoughts and the above, I recommend changing the short field to be the same length as region (varchar (35)).

This will need some proper testing (especially since I am unfamiliar right now with the full install process).

I am travelling over the next two days, will have it ready by Monday evening. Sounds good?


Mansoor

**Comment by benkeen** [comment]
That sounds great, thanks Mansoor! Cranking it up to 35 chars seems like the best approach. 

And whenever you can get to it is terrific! Thanks very much for looking at this one. :)

**Comment by benkeen** [comment]
I'll close this one in the meantime, since it's now moot.

**Pull request closed without merging**
