### PR TITLE
Deploy to Heroku

### PR DESCRIPTION
**Pull request by martyychang**
Added a **Deploy to Heroku** button, following instructions on the [Heroku Dev Center](https://devcenter.heroku.com/articles/heroku-button). The button and procedure were tested twice, resulting in the creation of two _free Heroku apps_ that are capable of generating random data sets.

### CODE REVIEW

**Comment by benkeen** [comment]
Nice @martyychang, this looks fascinating! I'll need a little time to look it over and understand it.

**Comment by intellectual-kid** [comment]
hi @benkeen 
any update on this pull request. because i can't see these changes in files.

**Comment by vivekmalikymca** [comment]
Hi @martyychang 

I tried to deploy on heroku but it is not working.  Getting following error.

-----> PHP app detected
 !     WARNING: Your 'composer.json' contains a non-'stable' setting
       for 'minimum-stability'. This may cause the installation of
       unstable versions of runtimes and extensions during this deploy.
       It is recommended that you always use stability flags instead,
       even if you have 'prefer-stable' enabled. For more information,
       see https://getcomposer.org/doc/01-basic-usage.md#stability
-----> Bootstrapping...
-----> Installing platform packages...
 !     ERROR: Couldn't load 'composer.lock'; it must be a valid lock
       file generated by Composer and be in a consistent state.
       Check above for any parse errors and address them if necessary.
       Run 'composer update', add/commit the change, then push again.
 !     Push rejected, failed to compile PHP app.
 !     Push failed

**Comment by martyychang** [comment]
Hmm... @vivekmalikymca I suspect the error is caused by the updates on Heroku over the past couple of years. This will probably need to be re-done to work on the latest Heroku offering.

**Pull request closed without merging**
