### PR TITLE
Support for C# as a Programming Language Export Type

### PR DESCRIPTION
**Pull request by fferegrino**
I added support for C# as a Programming Language by using Anonymous Types.

Apart from modifying the export plugin I also modified the DataType `Date`, to add the `formatCode` to its metadata, in order to parse the dates to a `DateTime` type for C#.

### CODE REVIEW

**Comment by benkeen** [comment]
Great stuff, @fferegrino! I'll check this out tonight after work.

**Comment by fferegrino** [comment]
Cool, let me know if you find anything odd.

**Comment by benkeen** [comment]
Looks great! Pity CodeMirror doesn't have a C# syntax highlighter mode, but no big deal.

**Comment by fferegrino** [comment]
Great, thanks! 
I'll stick around for possible issues & keep contributing to this amazing project.

**Pull request merged**
